# Generated by Django 3.1.7 on 2021-03-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20210325_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ties',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wins',
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pim',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='shots',
            field=models.IntegerField(default=0),
        ),
    ]
