# Generated by Django 3.1.7 on 2021-03-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20210326_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goalie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('number', models.IntegerField(default=0)),
                ('teamAbbreviation', models.CharField(max_length=3)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('savePercentage', models.DecimalField(decimal_places=3, max_digits=1000)),
                ('users', models.JSONField(null=True)),
            ],
        ),
    ]
