# Generated by Django 3.1.7 on 2021-04-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20210328_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalie',
            old_name='name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='number',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='savePercentage',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='teamId',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pim',
        ),
        migrations.RemoveField(
            model_name='player',
            name='points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shots',
        ),
        migrations.RemoveField(
            model_name='player',
            name='teamId',
        ),
    ]
