# Generated by Django 3.1.7 on 2021-04-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20210405_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalie',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='player',
            name='users',
        ),
    ]
