# Generated by Django 3.1.7 on 2021-04-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20210405_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalie',
            name='alternateCaptain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goalie',
            name='birthCity',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='birthCountry',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='birthDate',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='captian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goalie',
            name='currentAge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='currentTeam',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='firstName',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='height',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='lastName',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='nationality',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='primaryPosition',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='savePercentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='shootsCatches',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='teamId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='alternateCaptain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='birthCity',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='birthCountry',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='birthDate',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='captian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='currentAge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='currentTeam',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='faceOffPct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='firstName',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='lastName',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pim',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='plusMinus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='powerPlayGoals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='powerPlayPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='powerPlayTimeOnIce',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='primaryPosition',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shifts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='shootsCatches',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='shortHandedGoals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='shortHandedPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='shortHandedTimeOnIce',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='shotPct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='timeOnIce',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='users',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
