# Generated by Django 3.1.7 on 2021-04-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20210405_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalie',
            name='alternateCaptain',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='birthCity',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='birthCountry',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='birthDate',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='captian',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='currentAge',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='currentTeam',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='height',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='number',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='primaryPosition',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='savePercentage',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='shootsCatches',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='teamId',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='wins',
        ),
    ]
