# Generated by Django 3.1.7 on 2021-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20210405_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currentTeamId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='faceOffPct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='shotPct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
        ),
    ]
