# Generated by Django 3.1.7 on 2021-04-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20210406_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='currentTeamId',
            new_name='teamId',
        ),
    ]
