# Generated by Django 3.1.7 on 2021-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_auto_20210406_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalie',
            name='alternateCaptain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goalie',
            name='birthCity',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='goalie',
            name='birthCountry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goalie',
            name='birthDate',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='goalie',
            name='captian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goalie',
            name='currentAge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='currentTeam',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='evenSaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='evenShots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='evenStrengthSavePercentage',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='goalie',
            name='firstName',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='goalie',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='gamesStarted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='goalAgainstAverage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='goalie',
            name='goalsAgainst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='height',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goalie',
            name='lastName',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='goalie',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='nationality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goalie',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='ot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='powerPlaySavePercentage',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='goalie',
            name='powerPlaySaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='powerPlayShots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='primaryPosition',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='savePercentage',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='goalie',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='shootsCatches',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='goalie',
            name='shortHandedSavePercentage',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='goalie',
            name='shortHandedSaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='shortHandedShots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='shotsAgainst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='shutouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='teamId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='timeOnIce',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='goalie',
            name='timeOnIcePerGame',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='goalie',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
