# Generated by Django 3.1.7 on 2021-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(max_length=3)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=120)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
