# Generated by Django 3.1.7 on 2021-03-23 13:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20210323_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None),
        ),
    ]
