# Generated by Django 3.1.7 on 2021-03-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20210323_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
    ]
