# Generated by Django 3.1.7 on 2021-03-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20210323_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
