# Generated by Django 3.1.7 on 2021-03-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20210323_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.JSONField(null=True),
        ),
    ]
