# Generated by Django 3.1.7 on 2021-03-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20210323_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='link',
        ),
    ]
