# Generated by Django 3.1.7 on 2021-04-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_remove_team_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='firstYearOfPlay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='siteUrl',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
