# Generated by Django 3.1.7 on 2021-04-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_auto_20210405_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='siteUrl',
            new_name='officialSiteUrl',
        ),
    ]
