# Generated by Django 3.1.7 on 2021-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_auto_20210405_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='ties',
            new_name='ot',
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='faceOffWinPercentage',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='team',
            name='penaltyKillPercentage',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='team',
            name='powerPlayGoals',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='team',
            name='powerPlayGoalsAgainst',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='team',
            name='powerPlayPercentage',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='team',
            name='savePctg',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='team',
            name='shotsAllowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='shotsPerGame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='venue',
            field=models.JSONField(null=True),
        ),
    ]
