# Generated by Django 3.1.7 on 2021-04-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_auto_20210405_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='points',
            new_name='pts',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='gamesPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='shotsAllowed',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='shotsPerGame',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=100),
        ),
    ]
