# Generated by Django 3.1.7 on 2021-04-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_auto_20210405_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='faceOffsLost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='faceOffsWon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goalsAgainstPerGame',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='team',
            name='goalsPerGame',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='team',
            name='ptPctg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
        ),
    ]
