# Generated by Django 3.1.7 on 2021-04-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0023_auto_20210405_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ptPctg',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
        ),
    ]
